# Add these directives inside the existing HTTPS VirtualHost for:
# swapscholar36018014.japaneast.cloudapp.azure.com

ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/

RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"

ProxyTimeout 60
